### ISSUE TITLE
Research: create plan for e2e testing for frontend

### ISSUE THREAD

**Issue by fredo** [beamer-bridge/beamer#1012]
# description
In the past, former colleagues were looking into a full e2e test setup for the frontend.

We need to look into that again and make a plan what to create. 

# Acceptance criteria
- [x] Epic #384 has been reworked and sub issues are created
- [x] Current open issues that are related to frontend e2e should be sorted , merged or closed so that we dont have issues we dont need

**Comment by GabrielBuragev** [comment]
Used already created epic #384 to add the e2e issues in it.
All the test issues are now inside of it.

Since all the issues inside of it have pretty good descriptions, there was no need to add new ones or edit (for now). 
I will go through them one more time and maintain them in the near future based on the needs.
