### ISSUE TITLE
Adding a "I want to approve infinite sum" button 

### ISSUE THREAD

**Issue by DocSmoove** [beamer-bridge/beamer#1071]
# Rationale
We had several of our users complain/point out that it is a little weird our bridge is requesting to have access to their entire balance.
![image](https://user-images.githubusercontent.com/107990484/192210817-7ec6f808-93f7-4abb-ab7a-e4dc347321ee.png)

Alternatively, a community member has suggested a potential UX solution.
![image](https://user-images.githubusercontent.com/107990484/192210734-349f0a82-642e-4643-881d-46bed133dc68.png)

# Implementation

**Comment by fredo** [comment]
General question here? Does the user approve for the entire balance or for infinite amount? 
Those are two different values. 
The entire balance would indeed sound weird. Infinite amount is also risky but somewhat usual in the space.

**Comment by GabrielBuragev** [comment]
@fredo 
How [it's impemented currently](https://github.com/beamer-bridge/beamer/blob/main/frontend/src/services/transactions/token.ts#L20-L23), the allowance is given on the full token balance.

It could be adjusted to give allowance on the `minimumRequiredAmount` instead of `signerTokenBalance`.

Hint: `minimumRequiredAmount.asString` is holding the value of `tokenAmount` being sent + `fees`.

**Comment by GabrielBuragev** [comment]
Update to my previous comment:
The implementation has changed in PR #1103. Now users are prompted to give allowance to the request transfer amount (`minimumRequiredAmount`) every time they try to create a new request.

**Comment by czepluch** [comment]
This issue is estimated without the design efforts needed. @GabrielBuragev please create an issue for the design part.
