### ISSUE TITLE
Replace flake8, pylint and isort with ruff

### ISSUE THREAD

**Issue by istankovic** [beamer-bridge/beamer#1339]
https://github.com/charliermarsh/ruff is "An extremely fast Python linter, written in Rust."
We are already experiencing slow pylint and flake8 runs and we should try out ruff and replace what we can with it.
At the very least, it looks like we can replace flake8, pylint and isort.

**Comment by panpilkarz** [comment]
Did some research and timing measurements for each linter:

```
$ make lint
time mypy beamer/ scripts/
       18.82 real        11.13 user         0.97 sys

time black --check --diff beamer/ scripts/
        5.53 real         2.43 user         0.42 sys

time flake8 beamer/ scripts/
        1.12 real         2.99 user         0.28 sys

time isort beamer/ scripts/ --diff --check-only
        0.40 real         0.16 user         0.04 sys

time pylint beamer/ scripts/
        7.06 real        20.16 user         0.71 sys
```

`mypy` is the most time consuming check. Unfortunately `ruff` is not a good replacement for `mypy`. I did a small test by removing function return type hint and `ruff` didn't report it as expected according to the [FAQ](https://beta.ruff.rs/docs/faq/#how-does-ruff-compare-to-mypy-or-pyright-or-pyre):

> It's recommended that you use Ruff in conjunction with a type checker, like Mypy

Regarding second most time consuming check `pylint`, `ruff` [is a good replacement for pylint](https://beta.ruff.rs/docs/faq/#how-does-ruff-compare-to-pylint), so we could save 7 seconds (~20% of total time) on `make lint`. 

```
$ ruff beamer/ scripts/
real    0m0.471s
user    0m0.060s
sys     0m0.052s
```

**Comment by istankovic** [comment]
Thanks for doing the measurements!

Yeah, ruff is not a mypy replacement, but we can replace flake8, isort and pylint with it, which would save us ~8.5s, according to your timings, which is not a small saving.

**Comment by panpilkarz** [comment]
IMO there is no strong need for removing isort & flake8 after we have`pydifflint` - what do you think @istankovic?

___

If we go for it, replacement of `flake8` is pretty straightforward, because there is conversion tool for that: https://pypi.org/project/flake8-to-ruff/

Regarding replacing `isort`, ruff output is less helpful comparing to `isort --diff  --check-only`. 
```
$ ruff beamer/
beamer/agent/chain.py:1:1: I001 [*] Import block is un-sorted or un-formatted
beamer/agent/relayer.py:1:1: I001 [*] Import block is un-sorted or un-formatted
beamer/agent/util.py:1:1: I001 [*] Import block is un-sorted or un-formatted
beamer/middleware.py:1:1: I001 [*] Import block is un-sorted or un-formatted
beamer/tests/__init__.py:1:1: I001 [*] Import block is un-sorted or un-formatted
beamer/tests/agent/multiple_processors/_test_slave.py:1:1: I001 [*] Import block is un-sorted or un-formatted
beamer/tests/agent/test_rpc_errors.py:1:1: I001 [*] Import block is un-sorted or un-formatted
beamer/tests/contracts/test_request_manager_fees.py:1:1: I001 [*] Import block is un-sorted or un-formatted
```

It neither prints which line is wrong nor diff.

On the other side, if we run it with `--fix`, it will fix the code, similarly to `black`. What do you think @istankovic ?

**Comment by istankovic** [comment]
The major motivation for this issue was performance, of course, which is now helped with the new difflint targets (thanks!).

However, that was not the only motivation. One thing we had experienced is that different tools can have slightly different perspectives of how code should be formatted. So it happened before that e.g. `black` reformatted code that was deemed ok by `isort` and vice-versa. So this is another thing why I think we should reduce the number of different tools.

Finally, `ruff` seems to be gaining momentum in the wider Python community so I expect it will also attract more contributors and get feature parity with other tools, over time.

Regarding

> Regarding replacing isort, ruff output is less helpful comparing to isort --diff  --check-only.
[...]

I would say this is still ok. We do get some output and I assume the exit code is indicating an error so it should be fine.

So from my point of view, I'd still remove both `flake8` and `isort`.

By the way, what about `pylint`?

**Comment by panpilkarz** [comment]
Turns out `ruff` is not mature enough to replace `pylint`.

Following is the progress of filling the gap between pylint and ruff rules:
https://github.com/charliermarsh/ruff/issues/970

Based on that and the fact we have fast linting options via `difflint` now, lets just add `ruff` as an additional linter and keep existing ones. While having `ruff` and using it on daily basis, we gonna gain experience and have more input for further evaluation.

**Comment by istankovic** [comment]
We can close this now.
