### ISSUE TITLE
Research fee model

### ISSUE THREAD

**Issue by andfletcher** [beamer-bridge/beamer#1394]
the minimum lp fee is constructed by 2 transactions on the source chain (claim and withdraw), and one on the target chain (fill).
Currently we only have one fee per source chain. We need to find a way that accounts for different fees on different target chains.

One way could be to store a base fee for each chain inside of the RequestManager. Fees can then be constructed together depending on where the transfer should go to.

## Acceptance criteria
- [ ] Timeboxed research time on a design
- [ ] Present design to the team and make decision 
- [ ] Open any issues that might be needed

**Comment by andfletcher** [comment]
Timeboxed to 8 hours / 1 day max.

**Comment by fredo** [comment]
I think for now, it is the most straight forward way to compound fees from source and target chain fee values.
Another option would be to collect fees on the source chain for source chain related fees and reduce the amount sent on the target chain relative to the current target chain fees, but this would break lots of claims and would also be much more difficult to explain to the user. 

# Fee construction per chain
In order to allow a fee construction per chain, we would need a mapping from chain id to fee value.

Fees could be constructed in a more transparent way, compared to now, where we just set a value.
For the sake of simplicity, lets assume now that every transaction uses the same amount of gas. We have two transactions on the source chain and one on the target chain per transfer.
In order to simplify the stored values in the mapping, the mapping could reflect "normalized cost" per transaction. This is similar to the concept of `gas price` (price per unit).

Fee construction could be `fee = (normalized_fees[source] + normalized_fees[target]) * minLpFee * LP_MARGIN`

## Normalizing fees for all chains
What we are effectively doing with this approach is, normalizing all fees to the base of one specific chain. One suggestion here is that we can normalize all fees to L1 where the L1_fee_factor is always 1. Every other `normalized_fees` could be expressed in PPM.
minLpFee of a token would be then reflect the cost if all transactions are executed on L1. 
Additionally, and for better handling of the agent gains, we could introduce an LP_MARGIN value which is equal for all tokens. (This is optional as it could be incorporated into minLPFee).

## source and target factor
We need a source and target factor which could be incorporated into the fee factor which reflects the relative costs on source and target chain. These two factors are constant forever and could be incorporated into the fee value or could be immutable variables in the contract.

this would change the formula to

`fee = (SOURCE_FACTOR * normalized_fees[source] + TARGET_FACTOR * normalized_fees[target]) * minLpFee * MIN_LP_FEE_MARGIN`
