### ISSUE TITLE
Relayer for Ethereum

### ISSUE THREAD

**Issue by fredo** [beamer-bridge/beamer#1496]
The relayer needs to get another feature to be able to trigger L1 resolution coming from Ethereum.

It would be nice to stay with the same interface.
The contract could store a mapping from request_id to filler. currently the relayer receives tx_hashes as keys for a particular l1_resolution.
We could go with the same approach or try to use the request_id which is also bytes32. 

on the receiving side there is nothing to do (unlike Arbitrum)

**Comment by andfletcher** [comment]
Ivan suggests to have a talk on the detailed design.
Have sync meeting on it and then evaluate if 8 Storypoints is still doable. Can be done during the sprint.

**Comment by GabrielBuragev** [comment]
Outcome of today's meeting:

Since Ethereum will be treated as just another rollup we will need to somehow mimic the normal rollup behavior by using our own minimal implementation of an Outbox. Its purpose will be the store the fills that the protocol might need at a later point to resolve a dispute. 
We decided that, fee wise, it would be the smartest to just store hashes (of different params for the transfer) inside this Outbox contract which will be used later on, if ever necessary, in the process of L1 resolution. This will reduce the amount of storage required by this contract down to almost a minimum.

### Specifications for relaying in direction `ETH "rollup" -> AnyRollup`

The job of the relayer here will be to call this customized Outbox contract in order to initiate an L1 resolution. The relayer will need to provide raw parameters to the Outbox contract which will be used for calling the resolver as: 
```
Resolver.resolve(requestId, fillId, chainId, sourceChainId, msg.sender)
```
In order to be able to support such behavior inside the relayer we will need to do the following changes:
1. Adjust the relayer's design to support different sets of CLI arguments/options for each relayer service. Currently it only supports one set of options which satisfies the requirements of the currently supported rollups as they have a similar architecture (Outboxes, Inboxes etc...). With this we open the door for supporting more customized rollup implementations. 
2. Implement Ethereum relayer service

### Implementation
Implementing 1.:
Use the current design and apply typing changes (probably by using generics) to define the set of options per relayer service.

Implementing 2.:
At this moment we assume the `EthereumL1Messenger` & `EthereumOutbox` are implemented and we can start integrating it in our Ethereum relayer service. Define the new options for this service, and use them for calling the respective ethereum contracts.

@fredo Please check if i forgot something that is important.

**Comment by fredo** [comment]
looks good. 

Maybe it's worth mentioning that nothing is needed to be done for the `anyRollup` -> `Ethereum` direction

**Comment by fredo** [comment]
As discussed, we have a solution to maintain the interface between the agent and the relayer. 

The agent will pass the tx_hash to the relayer.
The relayer will read the events emitted by the tx. From there the relayer is able to rebuild the encoded call and will call the EthereumL2Messenger for resolution

**Comment by andfletcher** [comment]
Done
