### ISSUE TITLE
Add Beamer bridge to gnosise safe app (store)

### ISSUE THREAD

**Issue by andfletcher** [beamer-bridge/beamer#1507]
# Rationale
We want to be able to allow users to connect to gnosis safe vie our frontend, but also let them select beamer bride within the Gnosis App website / location.

# Implementation
On the technical side this shouldn't be hard:
https://docs.gnosis-safe.io/learn/safe-tools/sdks/safe-apps/get-started

The problem of course is that since we are not CRA app, we'll have some more work but doable.
As far as I understand the docs we just need to add a manifest.json file to our current app.
@GabrielBuragev maybe knows it better. I searched a little on how to add manifest.json file, but it seems that vite can only generate one file that we cannot modify:
https://vitejs.dev/guide/backend-integration.html

It seems we should use this plugin: https://vite-pwa-org.netlify.app/guide/

AFter adding our manifest, we can test our app through the gnosis safe interface. We should make sure that the app detects the currently connected gnosis safe as the address of the user and not the connected account in metamask.

## Additional information
https://github.com/beamer-bridge/product/issues/95

## Acceptance criteria
- [x] User can connect to their gnosis safe via our website --> links to gnosis safe and lists beamer on the page for users to interact and use
- [x] Criterias are fulfilled for us to get listed / released  https://docs.gnosis-safe.io/learn/safe-tools/sdks/safe-apps/releasing-your-safe-app

**Comment by GabrielBuragev** [comment]
@compojoom will test if connecting via walletconnect to gnosis safe is possible.

**Comment by andfletcher** [comment]
> @compojoom will test if connecting via walletconnect to gnosis safe is possible.

This would only partially fulfill this issue. Important for us is also to be visible on the safe website / app store page they have. For that we will need to do additional changes.

**Comment by GabrielBuragev** [comment]
I just took a quick look at this, it looks like it is very easily doable and no need for modifying the vite config files.
We could simply add the `manifest.json` file inside `public` folder and it will be included in the static build of the app.
After that, test the app by adding it as a custom app inside Safe's dashboard.

**Comment by compojoom** [comment]
well, if that works - even better!

**Comment by andfletcher** [comment]
@GabrielBuragev & @compojoom  we gave this 3 story points. If you belive this is totally wrong lets align.

**Comment by manuelwedler** [comment]
This issue needs some more thoughts than expected. We were not considering that a Safe only exists on one chain as it is a contract. It's possible to create the same Safe on another chain with the same address, but usually a user would not have taken that effort. This also implies that the `wallet_addEthereumChain` and `wallet_switchEthereumChain` RPCs are not implemented.

I would propose a few changes to the dapp if the user connects to a Safe provider:

1. Don't prefill the target address.
2. Show a warning if the user chooses the same address as the Safe. Just to make sure that the user is aware that they would have to actively create a Safe with the same address on another chain. (Btw: When the user's EOA's nonce was raised on the other chain it can get impossible to create a Safe with the same address there)
3. Disable the source chain selector. Just show the chain the Safe is deployed on, or an error if we don't support that chain.
4. Don't show the "Add token" button, simply because the related RPC is not implemented.

**Comment by manuelwedler** [comment]
I didn't implement your suggestion @compojoom . I think it would be just too much effort for a small improvement. We would have to add and maintain the ABIs of the Safe to properly implement that check I think.

**Comment by manuelwedler** [comment]
This is not completed yet. We are not listed in the Safe app. For this, we need to update our main deployment, open an issue against their repository and let them review our integration.

**Comment by manuelwedler** [comment]
The deployment is updated with latest fixes. I created the issue on their repo: https://github.com/5afe/safe-apps-list/issues/253
