### ISSUE TITLE
Data Sampling for fee calculation

### ISSUE THREAD

**Issue by compojoom** [beamer-bridge/beamer#1537]
To determine the optimal min fee we need to sample the on-chain data and check the fees that agent pay for making a transfer(fill, claim, withdraw) and the conversion rate eth/token.

## Acceptance criteria
-  [x] We have a ~script~ Dune SQL query that pulls the needed data ( costs of x days in the past for fill, claim, and withdraw with the info of which agent is connected with the costs) for each chain and calculates the average and median 
- [x] We have an initial conversion rate/price / faktor to in the formula for the ethereum integration launch (could be integrated in the spreadsheet, for ex. https://blog.coingecko.com/import-coingecko-cryptocurrency-data-into-google-sheets/)
- [x] Create nice google sheet for this showing the costs and the factors and the input with formula (will be maybe public viewable) + add a field / section for the number we get from #1538 

## Sampling size
No clear opinion on this since prices might change fast. We need to be sure that we get sufficient data in term of time and number of cost points.

**Comment by andfletcher** [comment]
The current challenge is still how to get the block when we start collecting the data without losing any events (or how many events are we fine missing?)

**Comment by compojoom** [comment]
@GabrielBuragev - I experimented a little:
https://dune.com/queries/2250280

I'm not 100% sure about approx_percentile https://trino.io/docs/current/functions/aggregate.html?highlight=percentile#approx_percentile

**Comment by GabrielBuragev** [comment]
Posting the recap of todays meeting here.

We will separate the work on this issue in two parts in order to not block the ethereum deployment:

1. Finalize the work that @compojoom already started - Use dune queries to get the avg./median values represented in ETH and manually paste those values in the spreadsheet which does the eth/usd conversion.
2. Automate the process by: calculating the avg./median fees (for a specific date range) by using a script which can be ran by anyone, incorporate those values in another script which is responsible for optimizing the final calculated minLpFee value by taking into account previous fee excess(+/-) & configuring the deployed contracts.

This is the most time optimized approach considering the time constraints for the next planned deployment.

---

Open questions:

- How to determine the price that will be used in the eth/usd conversion? Average is one approach but in order to account for price spikes and abnormally distributed transactions throughout the specified date range, a Weighted Average approach was proposed.

Follow up issues to be created, estimated and planned upon. 

Let me know if i missed something.

**Comment by GabrielBuragev** [comment]
Follow up issues created:
- https://github.com/beamer-bridge/beamer/issues/1601
- https://github.com/beamer-bridge/beamer/issues/1600
- https://github.com/beamer-bridge/beamer/issues/1599

Also, updated the issue description to reflect the most up-to-date acceptance criteria (based on our previous discussion).

**Comment by GabrielBuragev** [comment]
Beautiful spreadsheet can be found here: https://docs.google.com/spreadsheets/d/1WJ1SjngtY84Vo7uyVf3sfpigpU0Oy7UD-Wfa4_ZEAKo/edit#gid=400406010

Not so beautiful Dune SQL queries can be found here:
- https://dune.com/queries/2250280
- https://dune.com/queries/2255423

**Comment by compojoom** [comment]
I think it looks good.

I like the queries!

**Comment by GabrielBuragev** [comment]
Closing as completed.

Follow up optimization issue: https://github.com/beamer-bridge/beamer/issues/1620
