### ISSUE TITLE
Dune locked capital query wrong eth value

### ISSUE THREAD

**Issue by compojoom** [beamer-bridge/beamer#1543]
If there is an ongoing challenge the locked capital query https://dune.com/queries/1943563/3206487 will show wrong ETH amount  as we are fetching all claimerStakes and summing them. We should group the claims by claimer and challenger and take the last value.

**Comment by compojoom** [comment]
The correct query for this should be:

```
WITH claimerStake as (
SELECT max(CAST(claimerStake as DOUBLE)) as stake, claimId
     FROM
      beamer_bridge_v1_arbitrum.RequestManager_evt_ClaimMade
    where
      requestId not in (
        SELECT
          requestId
        FROM
          beamer_bridge_v1_arbitrum.RequestManager_evt_DepositWithdrawn
      )
      AND (
        CASE
          WHEN '{{agent}}' != 'all' THEN claimer = lower('{{agent}}')
          ELSE claimer != ''
        END
      )
      GROUP BY claimId
)

SELECT SUM(stake) / 1e18 from claimerStake
```

The reason I didn't update the query is that we are losing the decimal precision when working with DOUBLE and this is especially visible when converting `316500000000000001` to double and we end up with: `316500000000000000`

At this time I'm not sure how to deal with this, because dividing by `1e18` we end up with: `0.3165` and this basically misses 1 wei, which is not ideal.

**Comment by GabrielBuragev** [comment]
Since we don't need precision down to the last decimal in the "Agent locked capital" query i decided to proceed with fixing the query itself. 
After getting some clarification from the Dune team we can plan the next steps for tackling the precision issue.

Here is the new query:
https://dune.com/queries/2177680/3567253?agent_e15077=all

As an extra, i included DAI in it.

**Comment by compojoom** [comment]
look good.
