### ISSUE TITLE
Research frontend handling reorgs

### ISSUE THREAD

**Issue by fredo** [beamer-bridge/beamer#1573]
The frontend might need to adapt for reorgs. 

Especially when sending the request tx and when waiting on events like RequestFilled, RequestClaimed, etc. 

Timeboxed issue for researching what needs to be done

**Comment by GabrielBuragev** [comment]
Based on my research, the current frontend code is prone to errors due to re-org events after we land on Ethereum. 
I propose adding the following:
- Define a confirmation time (in blocks) per chain which the app consumes in order to determine the "finality" of a transaction
- Consume the defined confirmation time by waiting on each transaction execution until the transaction reaches "finality"
- When listening on events via filters, make sure to check for the event transaction finality before acting upon.
