### ISSUE TITLE
Agent Challenge Tests Goerli V2

### ISSUE THREAD

**Issue by fredo** [beamer-bridge/beamer#1631]
### Setup

- [x] Setup agents in server for goerli

### Test
* make a transfer request
* make a transfer request
* make sure the request is filled by one of the agents
* challenge the corresponding claim
* check whether the agent responds to the challenge
* wait for the fill message to finalize
* make another challenge (within the same challenge game) with enough funds to go to L1
* make sure the agent triggered L1 resolution
* wait for the results to appear on the source chain
* check that the agent was able to withdraw

# Ethereum
- [x] make a transfer request
- [x] make sure the request is filled by one of the agents
- [x] challenge the corresponding claim
- [x] check whether the agent responds to the challenge
- [x] wait for the fill message to finalize
- [x] make another challenge (within the same challenge game) with enough funds to go to L1
- [x] make sure the agent triggered L1 resolution
- [x] wait for the results to appear on the source chain
- [x] check that the agent was able to withdraw

# Optimism
- [x] make a transfer request
- [x] make sure the request is filled by one of the agents
- [x] challenge the corresponding claim
- [x] check whether the agent responds to the challenge
- [x] wait for the fill message to finalize
- [x] make another challenge (within the same challenge game) with enough funds to go to L1
- [x] make sure the agent triggered L1 resolution
- [x] wait for the results to appear on the source chain
- [x] check that the agent was able to withdraw

# Arbitrum
- [x] make a transfer request
- [x] make sure the request is filled by one of the agents
- [x] challenge the corresponding claim
- [x] check whether the agent responds to the challenge
- [x] wait for the fill message to finalize
- [x] make another challenge (within the same challenge game) with enough funds to go to L1
- [ ] make sure the agent triggered L1 resolution
- [ ] wait for the results to appear on the source chain
- [ ] check that the agent was able to withdraw

**Comment by GabrielBuragev** [comment]
Resolutions coming in direction "ARB -> Any Network" & "ETH -> Any Network" worked, however, resolutions coming in direction "OP -> Any Network" are still pending (~16 hours after initialization).

The Optimism Relayer cannot relay the message due to the message being stuck with status "STATE_ROOT_NOT_PUBLISHED".
Confusingly enough, L1 <-> L2 block submission is working fine when we look at: https://goerli-optimism.etherscan.io/txsEnqueued

I also tried updating the Optimism SDK used inside the relayer just in case it was outdated but that didn't help as well.

Fill transaction that is stuck on OP can be found here: https://goerli-optimism.etherscan.io/tx/0x49fec16d0f3c26799737928059faef8e61d313c27d1652e1bb5ff6c119e94403
