### ISSUE TITLE
Deployments: Setup npm package

### ISSUE THREAD

**Issue by GabrielBuragev** [beamer-bridge/beamer#1727]
# Rationale
In order to be able to consume different versions of the deployments folder by any other TS/JS module of our codebase we need the deployments folder to be setup and published as an npm package (on a regular basis/whenever we redeploy).

What are the use-cases?
Frontend & relayer will be able to easily specify and consume different versions of the deployments folder in order to test/debug/deploy different versions of the frontend easily.

# Implementation
- Add package.json inside deployments folder
- Add CI workflow for publishing npm package once we have a new deployment
- Use dev versions between major contract version releases (similar to [trustlines](https://www.npmjs.com/package/@trustlines/trustlines-contracts-abi?activeTab=versions))
- Decide if we want to move the contract type generations to the deployments folder instead of the frontend folder. We currently use the same approach for generating the types inside relayer & frontend. Would be good to have this only on one place.

# Acceptance Criteria
- [ ] Folder is properly setup as an npm package with a package.json file
- [ ] CI workflow implemented

**Comment by compojoom** [comment]
We've spent a lot of time on this last week, but after thinking about the problem over the weekend I personally think that we approached the issue from the wrong perspective.

The description states:

> In order to be able to consume different versions of the deployments folder by any other TS/JS module of our codebase we need the deployments folder to be setup and published as an npm package (on a regular basis/whenever we redeploy).

From that we went on to assume that we need some javascript in the package that exposes access to the deployment files. 

We created an API to access the deployment and abi files. Someone who uses the package wouldn't have to import the files directly, but rely on our API functions:
`getBaseDeployment(contractName, deployment: mainnet | goerli)`
`getRollupDeployment(contractName, chainId, deployment)`
`getAbi(contractName, deployment)`

This of course is very cool! It feels right to have this, and we feel as "awesome architects". Unfortunately when implementing this we have to take into consideration the fact that the package is going to be consumed both by node processes, and by websites. 

The main issue here are websites. Depending on how we include the json files in the package we might end up with all json files in the final website bundle, despite the fact that we only use 1 single file from the npm package. 

E.g.
```
Import BaseDeploymentMainnet from '@breamer-bridge/deployments/artifacts/mainnet/base.deployment.json'
Import BaseDeploymentGoerli from '@breamer-bridge/deployments/artifacts/goerli/base.deployment.json'

const bases = {
mainnet: BaseDeploymentMainnet,
goerli: BaseDeploymentGoerli
}

export const getBaseDeployment = (contractName, deployment) => {
return basese[deployment][contractName]
}
```

Now if the user wants to use getBaseDeployment for 'mainnet' his bundle will end up with goerli as well, since the bundler doesn't know which deployment the user will end up using at runtime. 

Something that can work for this kind of a problem are dynamic imports.
What we could do is instead of importing the base.deployment.json files and creating a mapping of the json content, we use await import syntax to fetch the files at runtime. An implementation might look something like this:
```
export const getBaseDeployment = async (contractName, deployment) => {
if (mainnet) {
return await import('@breamer-bridge/deployments/artifacts/mainnet/base.deployment.json')
}
if(goerli) {
return await import('@breamer-bridge/deployments/artifacts/mainnet/base.deployment.json')
}

throw Error('...')
}
```

With this code what the bundler would do is - it will see that it needs to import 2 files dynamically at runtime, it will copy the files to the distribution folder, but won't include them in the main bundle file. At runtime depending on which file the user wants to access it will fetch it. This way the distribution folder will still end up with all .json files from the package, but they won't be forced up on the user. Instead those files will just lie around on server and might be fetched if necessary, but the bundle size will stay constant.

That's good, but it also poses a problem. One popular way to support dynamic imports in bundlers is the rollup/plugin-dynmic-import-vars plugin:
https://github.com/rollup/plugins/tree/master/packages/dynamic-import-vars#limitations

One could have variables in the dynamic import and plugin will create a glob pattern out of that variable and include all json files in the distribution folder. Unfortunately for us it seems that there is a bug when running vite in dev mode with it and vite is not able to fetch the json files. (the production build contains the files). Without debugging vite itself + the rollup plugin the only solution we can come up with is to basically expose all possible export paths manually.

https://github.com/beamer-bridge/beamer/blob/npm_package/deployments/src/constants.ts

```
export const deploymentsImportMap: DeploymentMap = {
    'mainnet': {
        'base': () => import(`../artifacts/mainnet/base.deployment.json`),
        '1-ethereum': () => import(`../artifacts/mainnet/1-ethereum.deployment.json`),
        '10-optimism': () => import(`../artifacts/mainnet/10-optimism.deployment.json`),
        '42161-arbitrum': () => import(`../artifacts/mainnet/42161-arbitrum.deployment.json`),
    },
    'goerli': {
        'base': () => import(`../artifacts/goerli/base.deployment.json`),
        '5-ethereum': () => import(`../artifacts/goerli/5-ethereum.deployment.json`),
        '420-optimism': () => import(`../artifacts/goerli/420-optimism.deployment.json`),
        '84531-base': () => import(`../artifacts/goerli/84531-base.deployment.json`),
        '421613-arbitrum': () => import(`../artifacts/goerli/421613-arbitrum.deployment.json`),
    },
}

export const abisImportMap: abiMap = {
    'mainnet': {
        'ArbitrumL1Messenger': () => import(`../mainnet/ArbitrumL1Messenger.json`),
        'ArbitrumL2Messenger': () => import(`../mainnet/ArbitrumL2Messenger.json`),
        'EthereumL1Messenger': () => import(`../mainnet/EthereumL1Messenger.json`),
        'EthereumL2Messenger': () => import(`../mainnet/EthereumL2Messenger.json`),
        'FillManager': () => import(`../mainnet/FillManager.json`),
        'OptimismL1Messenger': () => import(`../mainnet/OptimismL1Messenger.json`),
        'OptimismL2Messenger': () => import(`../mainnet/OptimismL2Messenger.json`),
        'RequestManager': () => import(`../mainnet/RequestManager.json`),
        'Resolver': () => import(`../mainnet/Resolver.json`),
    },
    'goerli': {
        'ArbitrumL1Messenger': () => import(`../goerli/ArbitrumL1Messenger.json`),
        'ArbitrumL2Messenger': () => import(`../goerli/ArbitrumL2Messenger.json`),
        'EthereumL1Messenger': () => import(`../goerli/EthereumL1Messenger.json`),
        'EthereumL2Messenger': () => import(`../goerli/EthereumL2Messenger.json`),
        'FillManager': () => import(`../goerli/FillManager.json`),
        'MintableToken': () => import(`../goerli/MintableToken.json`),
        'OptimismL1Messenger': () => import(`../goerli/OptimismL1Messenger.json`),
        'OptimismL2Messenger': () => import(`../goerli/OptimismL2Messenger.json`),
        'RequestManager': () => import(`../goerli/RequestManager.json`),
        'Resolver': () => import(`../goerli/Resolver.json`),
    },
}
```

Now this poses an obvious problem. Whenever we deploy to a new rollup, we need to also update the deplyomentImportMap - otherwise if we just publish a new npm version, despite the fact that the new rollup artifacts will be in the npm package, the API function won't be able to return that new rollup artifacts. 

After having a lot of discussions and thinking of having a script to generate the above mappings and then having a test to test whether the mappings were properly generated I think that the implementation details actually pushed us in the wrong direction. 

How is the frontend currently consuming the deployments?
The frontend copies the abis it relies on to frontend/src/assets. The script that generates the frontend config generation scripts are scanning the complete deployments folder, reading all the files and extracting the contract addresses. Yes, here it would be pretty cool to have `getRollupDeplyoment('RequestManager', 'mainnet').address`, but is this really necessary?

We wanted the npm package because we wanted to simplify release and test process of the frontend. Right now - the frontend might have some changes and we would like to test it against the latest deplyoment, or an earlier deployment. We would have to checkout the specified commit, copy the deployment files etc. never knowing whether we have are actually using the deployment we wanted to use. 
The npm package solves this by having a version. I know that @beamer-bridge/deployments@v99 - contains a new rollup that I want to test against - so I install that version and test.

More or less, same goes for the relayer. We just want to use the package to specify the correct addresses. 

So, how about instead of us guarding the JSON files through an API, we allow the user to directly use them.

If my application needs the RequestManager Abi, I just import:
import RequestManager from 'abis/mainnet/RequestManager'

If my application needs to be able to switch between mainnet and goerli, than it would be my responsibility to include and optimize those files for my bundler. 

This of course also has a drawdawn - instead of having a clear set of APIs to access contract data the user would now need to know the structure of the json file. Here we have to note that the current API we've designed also suffers from that problem, since we were basically returning parth of the JSON object, so the user had to then access props on that object. If we tomorrow decide to change the `address` prop to `addr`, then despite our API the user application is going to break. 

So with my current understanding I think that the correct thing to do would be to just package the .json files without providing an API and let the user grab the files he needs from that package. 
Benefit for us - no code to maintain... No need to write scripts to update some files with paths to other files, no complicated release process of that npm script. 

The negative is, I don't know, maybe the fact that the user would now have to inspect the package files to know what to include, but I don't think this is that bad.

**Comment by istankovic** [comment]
[...]

Thanks for the writeup, @compojoom!

I like the only-abi-files-are-packaged approach very much.

Regarding the data changes, note that the ABI files are actually produced by `solc`, not by us, so I don't expect the ABI structure to change much, if at all. So, if I am understanding this correctly, we would have something like

- we push a new/modified deployment to our github repo
- the CI is triggered
- in CI, a special npm package workflow invokes the script to generate the ABI (with _only_ ABI info)
- compute the new npm package version [**]
- if the version already exists in npm registry, do nothing
- otherwise, publish all generated ABI files (and only them) under the new version

Then the user would need to just download the specific npm package version and import the ABI
just like you mentioned above. The rest can be done by whatever tools one prefers.

In fact, I also like this approach because we ship just the ABI, we do not assume that
the user of our deployment files will use any specific library or framework. So they are free to
feed the ABI to whatever they use.

[**] the new version could be computed by e.g. `hash(hash(abi_file_1) | hash(abi_file_2) | ... | hash(abi_file_n))`,
        where the filenames are sorted.

**Comment by GabrielBuragev** [comment]
I see that this will open the way forward and for the time being it will be sufficient indeed (at least for our use cases).

I do feel like we could do a better job at abstracting this in the future so we can enable easy integrations on the JS/TS side by providing an API that is self explanatory. I will create an issue for this so its not forgotten but i think this will anyway be our main focus in the next quarter as we want to focus on integrations.

@istankovic i also suggest we take a look at how we can create a separate publishing pipeline for python so we offer the ABIs as a py package as well. This will be really useful for people that have or want to write their own arbitrage/any kind of bots and use beamer in their bot for fast bridging their assets to fill their operations.
I can create an issue for this as well.

**Comment by compojoom** [comment]
> In fact, I also like this approach because we ship just the ABI, we do not assume that
> the user of our deployment files will use any specific library or framework. So they are free to
> feed the ABI to whatever they use.

Exactly!

Also about the npm registry - as @GabrielBuragev  pointed on friday - if there is any change in the artifacts, we should create a new version - what are the chances that this change in the artifacts is already pushed as an npm package???

CI checks whether files have changed in artifacts, if they are run the script to generate new package and push. If filies were not changed, then we don't push anything.

I'm still not sure about the npm package changelog. It would be nice to have this. 
# Changelog
+ added rollupX deployment artifacts
+ added rollupY deployment artifacts.

**Comment by istankovic** [comment]
> Also about the npm registry - as @GabrielBuragev pointed on friday - if there is any change in the artifacts, we should create a new version - what are the chances that this change in the artifacts is already pushed as an npm package???
> 
> CI checks whether files have changed in artifacts, if they are run the script to generate new package and push. If filies were not changed, then we don't push anything.

Ah, yes, I forgot about that... (`deployments` contains both `config` and `artifacts`, and the check needs to be more specific: considering just changes to `deployments/artifacts` -- thanks for pointing that out!).

> I'm still not sure about the npm package changelog. It would be nice to have this.
> # Changelog
> 
>     * added rollupX deployment artifacts
> 
>     * added rollupY deployment artifacts.

How about just `git log --oneline  -- deployments/ | cut -d' ' -f2-`?
Currently this gives us
```
feat: add remaining deployment config files
feat: add new style goerli deployments
feat: add new style mainnet deployments
feat: create new config for goerli
feat: create new config for mainnet
deployment: add goerli deployment
deployment: deployment artifacts v2
deployments: change to use new structure
chore: remove mentionings of rinkeby
deployments: add new mainnet deployment
deployment: v1 contracts on goerli
deployments: deploy on Goerli testnet
deployments: mainnet: update the commit ID to correspond to the contract source
deployments: update mainnet deployment after redeploying request managers
deployments: mainnet: update with new Boba deployment
deployments: add mainnet deployment files
deployments: add a new Rinkeby deployment
deployment: Rinkeby deployment
Revert part of "Update contracts configuration in frontend"
Update contracts configuration in frontend
chore: Deploy new testnet contracts
add new rinkeby deployement files
Add current rinkeby test deployment
Remove outdated deployments
deploy: Add new rinkeby deployment
```

but we can of course limit the log to only those that changed since last time.

And then there is the question of more descriptive commit messages, but that we have anyway.

**Comment by istankovic** [comment]
> @istankovic i also suggest we take a look at how we can create a separate publishing pipeline for python so we offer the ABIs as a py package as well. This will be really useful for people that have or want to write their own arbitrage/any kind of bots and use beamer in their bot for fast bridging their assets to fill their operations.

Sure, but I wouldn't rush that right now. We need to think of a nice naming, which would be in line with the npm package name, as far as that is possible. Which name are you going to publish under?

**Comment by istankovic** [comment]
> CI checks whether files have changed in artifacts, if they are run the script to generate new package and push. If filies were not changed, then we don't push anything.

One question here. Where do you intend to keep track of the package version?
Do we need a `package.json` in the repo at all?

**Comment by compojoom** [comment]
yes, every npm package needs a `package.json`. But actually good question on the version number. Since the version number is in the file...
If we just increment the version number through a script on CI, the new version number won't be in the package.json and the next time we release again - we will have the same version. Maybe instead of automatic releases we go for tags again?

Maybe this is a required step after a deployment?

**Comment by compojoom** [comment]
@istankovic on npm I've reserved the `@beamer-bridge` organisation. I was planning on releasing the package under the name `@beamer-bridge/deployments`

**Comment by GabrielBuragev** [comment]
>If we just increment the version number through a script on CI, the new version number won't be in the package.json and the next time we release again - we will have the same version. 

Maybe we can use `npm version <major|minor|patch>` command. This updated the package.json as well. Check out https://docs.npmjs.com/cli/v8/commands/npm-version#description

**Comment by istankovic** [comment]
>  If we just increment the version number through a script on CI, the new version number won't be in the package.json and the next time we release again - we will have the same version. Maybe instead of automatic releases we go for tags again?
> Maybe this is a required step after a deployment?

That is a good question. I think we need to think more about how it's going to work.
In general, I see two options: (1) update the version number manually and commit it to `package.json` in the repo or, (2) let the CI do all the work

In (2) I would prefer the version information entirely from the repo because it would be auto-generated by the CI. However, in this case we need a way to get the "current" version so that we have something to increment. So in this scenario I don't think it makes sense to even have the version number tracked by the repo.
