### ISSUE TITLE
Relayer for Polygon zkEVM

### ISSUE THREAD

**Issue by fredo** [beamer-bridge/beamer#1747]
as defined in #1487 the relayer needs to claim messages from and to polygon zkEVM. It is the same interface. 

```sol
interface IBridgeMessageReceiver {
    function onMessageReceived(
        address originAddress,
        uint32 originNetwork,
        bytes memory data
    ) external payable;
}
```

[source](https://github.com/0xPolygonHermez/code-examples/blob/main/zkevm-nft-bridge-example/contracts/polygonZKEVMContracts/interfaces/IBridgeMessageReceiver.sol#L8-L14)

The payload could be fetched from the events, the native bridge emits.

```sol
    event BridgeEvent(
        uint8 leafType,
        uint32 originNetwork,
        address originAddress,
        uint32 destinationNetwork,
        address destinationAddress,
        uint256 amount,
        bytes metadata,
        uint32 depositCount
    );
```

[source](https://github.com/0xPolygonHermez/code-examples/blob/main/zkevm-nft-bridge-example/contracts/polygonZKEVMContracts/PolygonZkEVMBridge.sol#L101-L110)

@GabrielBuragev please revise if information are missing.

**Comment by GabrielBuragev** [comment]
From the first look of their documentation & SDK we managed to narrow down the steps/actions the relayer needs to take in order to relay messages from and to Polygon zkevm.

In general, their bridge infrastructure consists of only [1 contract](https://github.com/0xPolygonHermez/zkevm-contracts/blob/main/contracts/PolygonZkEVMBridge.sol) deployed on both Polygon ZKEVM & Ethereum Mainnet/testnet. This contract provides an easy-to-understand interface for both bridging a message (on source chain) & claiming a message (on destination chain).

What are the required actions in the relayer?
---
### Message Direction: _Polygon_ -> _Any rollup_

Here, before the relayer steps in, we assume that there is a message already being sent (to the **PolygonBridge**) by the **PolygonL2Messenger** with a specific `tx_hash` on the L2 side.

Relayer is called with the L2 `tx_hash` and needs to do the following:

1. Check the logs of the `tx_hash` and look for an emitted [BridgeEvent](https://github.com/0xPolygonHermez/code-examples/blob/main/zkevm-nft-bridge-example/contracts/polygonZKEVMContracts/PolygonZkEVMBridge.sol#L269). If there is none, obviously, throw an exception.
2. From this event the relayer should be able to extract most of the parameters it needs for claiming the message on the destination chain.
3. After fetching these parameters, the only thing missing is the merkle proof. By calling a specific RPC endpoint with the previously fetched parameters one can get the merkle proof. Here is an example on how to do that: https://github.com/0xPolygonHermez/code-examples/blob/main/zkevm-nft-bridge-example/scripts/claimMockNFT.js#L61
4. Now we are ready for claiming the message on the destination chain. This can be done by calling the `claimMessage` on the PolygonZKEVMBridge on the destination chain by using all the previously fetched parameters (again, consult with the example above).
5. Check if message was succesfully relayed/claimed on the destination. Here is an example method from their SDK that does that: https://github.com/maticnetwork/matic.js/blob/master/src/zkevm/zkevm_bridge.ts#L135
We could go an extra step here and verify that the message arrived on the RequestManager.


### Message Direction: _Any rollup_ -> _Polygon_
Here, the Polygon relayer implementation needs to take care of finalizing (claiming) the message sent from the source rollup. Sending the message to the **PolygonBridge** is already taken care of by the other relayer implementations & contracts.

The polygon relayer is called with the L1 `tx_hash` instead. The steps are the same as for the other direction.


Note 
---
This can be done with or without the [Polygon SDK](https://wiki.polygon.technology/docs/develop/ethereum-polygon/matic-js/zkevm/initialize-zkevm).

Pros of using the Polygon SDK:
- Utility functions for preparing the payload (step 1,2,3) with one method call (https://github.com/maticnetwork/matic.js/blob/master/src/zkevm/bridge_util.ts#L97)
- Utility functions for checking if a message has been claimed (https://github.com/maticnetwork/matic.js/blob/master/src/zkevm/zkevm_bridge.ts#L135)

Cons:
- Increases the size of the relayer bundle by roughly ~25 MB (https://packagephobia.com/result?p=%40maticnetwork%2Fmaticjs)

**Comment by GabrielBuragev** [comment]
Polygon ZKEVM RPC node endpoints can be found here: 
https://github.com/0xPolygonHermez/zkevm-node/blob/develop/docs/json-rpc-endpoints.md

**Comment by fredo** [comment]
Nice, that the Polygon SDK has support of zkEVM already. 
I just looked into the endpoints of getting the data which is `bridge-api.RPC_ENDPOINT`. There is no real documentation for it and the underlying server which runs on this endpoint is `https://github.com/0xPolygonHermez/zkevm-bridge-service`. 
The requests we need to make are luckily not too complex. 
Endpoints can be found `https://github.com/0xPolygonHermez/zkevm-bridge-service/blob/develop/proto/src/proto/bridge/v1/query.proto` which point to `https://github.com/0xPolygonHermez/zkevm-bridge-service/blob/develop/server/service.go`
