### ISSUE TITLE
Frontend: unpredictable gas limit error 

### ISSUE THREAD

**Issue by andfletcher** [beamer-bridge/beamer#1769]
#### System information
Discord User:
For some reason, I had multiple "UNPREDICTABLE_GAS_LIMIT" errors when I tried to use MetaMask extension (tried to bridge from Arb to OP and vise-versa); for testing purposes, I checked & transfered with MetaMask bridge and it was successfully; then I switched to Zerion Wallet and finally I was able to bridge with Beamer. maybe the issue is related to low asset allowance, and if so, maybe it worth to add some friendly explanation to user in UI in general, keep going, team, the product looks well!

**Comment by manuelwedler** [comment]
I had a look at this again. The issue is that the user approved less tokens than needed. Meaning that they did not use the `Use default` button for approval inside MetaMask. When creating the request transaction, we should again check if the right amount is approved. This would at least allow for showing an understandable error message or let us trigger another approval.

In the best case, we make MetaMask to prefill the field with our `default` amount, but I couldn't find an option for this yet.
