### ISSUE TITLE
Contract verification

### ISSUE THREAD

**Issue by palango** [beamer-bridge/beamer#328]
This epic groups issues related to contract verification.
The deployment script should be able to verify the deployed contracts.
We should be able to verify Beamer contracts on
- Boba
- OP
- Arbitrum

**Comment by czepluch** [comment]
#444 potential duplicate

**Comment by palango** [comment]
From #444:

The current testnet contracts should be verified. It's possible to do so on both Boba and Metis testnets through http://sourcify.dev/. We should also incorporate automating this into our deployment script.

**Comment by istankovic** [comment]
> @istankovic Have you tried verifying it on METIS?

METIS isn't even in the list of supported chains on sourcify, which I asked about in their Matrix channel, but got no reply.

**Comment by fredo** [comment]
This should be pulled into the backlog once we are working on the new deployment infrastructure. 
We need to find a solution though.
An alternative approach which turned out to be successful is verification on the explorer directly. According to @compojoom description we need to fold all imports into one file. For the current version such a document can be found [here](https://gist.github.com/fredo/01d53f36a8eede4f00a1ec23ab4ddd30). In any case, this should also be automated upon deployment.

**Comment by fredo** [comment]
closing this in favor of #619
