### ISSUE TITLE
contracts: map finalization time per chain id

### ISSUE THREAD

**Issue by fredo** [beamer-bridge/beamer#426]
we should rename the challengePeriod variable to finalization time (or something similar). 

In our convention the challengeperiod is the complete time until a challenge expires

the initial challengePeriod is computed as:

`challengePeriod = finalizationTimes[targetChain] + challengePeriodExtension`

since finalization times are defined per roll up we should have a mapping for that

**Comment by cducrest** [comment]
You may want to have different request managers (also, resolution registry, resolver) for each pair of bridged roll-up, instead of having a single contract with a mapping from chain ID to variable. It may be that in the future we have more difference based on the target roll-up, e.g. fees or rules for fill ID, which will be harder to implement if we use a single contract for every roll-up.

**Comment by fredo** [comment]
That's a good point. I think that once we start implementing multiple contracts per chain, then this will introduce a bigger change, which will also require to change the proposal of this issue.
Are you okay, with posponing it to then?

**Comment by palango** [comment]
Closed in #459
