### ISSUE TITLE
Preselect token to transfer after connecting to Metamask

### ISSUE THREAD

**Issue by istankovic** [beamer-bridge/beamer#448]
We currently preselect one of the rollups from frontend config for the `From` field. (Why don't we select another rollup from the config for the `To` field?)

It would be nice if we also did pre-selection of the token to be transferred, as soon as the frontend connects to Metamask.
We could choose the first token that has nonzero balance on the pre-selected `From` rollup.

With this and pre-selection of the `To` rollup we could further improve the user experience and potentially reduce the number of actions required.

**Comment by weilbith** [comment]
@olympe-silve your feedback? Do you think this makes sense UX wise?

**Comment by istankovic** [comment]
@olympe-silve could you please provide feedback?

**Comment by olympe-silve** [comment]
I don't have a strong opinion about this. I think it's potato-potato in terms of UX when there are so few networks involved.

My instinct is that it is a bit confusing to have specific rollups and token preselected. I would rather the fields to be left blank with instructions. But I looked into the UX research on the matter and couldn't find conclusive studies on the matter. 

@GabrielBuragev what do you think ?

**Comment by GabrielBuragev** [comment]
I also agree with you @olympe-silve on this one. I do believe that it might be confusing to have pre-selected chains/tokens, especially with the current implementation. 
If we add the pre-select feature, that will also mean we are forcing them to choose a network and possibly even add that network to their wallet provider, while their intention was to find and use another network of their preference. This could lead to extra clicks (for canceling the actions, changing networks) and a complete page reload due to [best practices](https://docs.ethers.io/v5/concepts/best-practices/).

**Comment by GabrielBuragev** [comment]
Note: We only preselect the rollup in the select component if the selected network on the connected wallet matches one of the available rollups in the selection.

**Comment by istankovic** [comment]
Thanks for the feedback, I'm going to close this since nothing needs to be done.
