### ISSUE TITLE
Create frontend config update script

### ISSUE THREAD

**Issue by nekhaly** [beamer-bridge/beamer#564]
# Rationale

We need to make sure that frontend configurations are always up to date with backend. There are contract ABIs and deployed contract addresses that are changing and they should be reflected on frontend configuration and assets. 

# Implementation

The idea is to create a script that copies ABIs to the frontend assets folder and also parses the deployment configuration file to get addresses for newly deployed contracts. The script runs before building the app and would support different sources for configuration for different variants (testnet, mainnet, dev...etc)

**Comment by weilbith** [comment]
@istankovic and I discussed this topic again today in person. Here I note down the result of this meeting and would please @nekhaly to make comment of what he things about it and if he agrees.

First of all, the frontend depends on the contracts. As a conclusion, the contracts are not responsible to manage the deployment data for the frontend, but the other way around.

Second, the ABI data is a build time dependency, while the deployment data (in fact the contract addresses) are a runtime dependency. The first part only implicit for now and will be tackled with #549. Second part will result into a file in the `public` directory of the frontend that will be fetched by the users web-browser and is basically part of the configuration store. With this approach it is also easy to exchange deployment information for running builds without re-building everything. Though this skips the compatibly checks, as long as we don't add them somehow different.

To make this work convenient, we will add a `yarn` script that copies the static files from the deployment directory in the repository to the `public` directory of the frontend. To make this more stable for breaking changes (in fact also removals), these information will be placed into a subdirectory, so the whole directory can be replaced. The pseudocode looks like that: `rm --recursive --force ./public/deployments && cp --recursive ../deployments ./public`.

Next to that we will create a `postinstall` hook script for `yarn` to run the former script. This means when you run `yarn install` the deployment information will be copied for you. And the same for the `build` script which will then run first the script to get the latest known deployment information. In between, in fact for an developer actively developing with a `dev` server, he can manually trigger the update too.

Very important is that the deployment data within the `public` directory will not be put under version control, but get a new `.gitignore` entry. This is generated data and more importantly already once in the repository. This is a mono-repository, so components are expected to align with each other. Anyways, if it should become necessary, it is as easy as having script that does a `git pull --depth=1 --commit=<special_version> <beamer_remote> $(mktmp --directory)`  and copies the `deployments` directory from there. 

Finally, working on #549 will just extend this process and generates the `*.d.ts` and factory files. Again, not under version control. Done with the `postinstall` hook and before every production build. The positive effect here is now also that if the contracts changed in a breaking manner, the build will fail due to the type system.

@istankovic please check if everything is right and if I forgot something.

**Comment by istankovic** [comment]
> @istankovic please check if everything is right and if I forgot something.

Everything is pretty much as we discussed. :+1: 

I would just add that, whatever we do, we should document the thing at `https://docs.beamerbridge.com/contributing.html`, the section on frontend.

**Comment by nekhaly** [comment]
Sounds good! Upon that, I added #549 as a dependency for this one!

**Comment by weilbith** [comment]
> Sounds good! Upon that, I added #549 as a dependency for this one!

I'm not 100% sure about the usage of "dependency" here. As I tried to explain above this a two-step process for me. First just without the types and then adding the types of top of it. So #549 must not be completed first before this issue can be done. Rather the opposite.
