### ISSUE TITLE
Allow users to withdraw expired requests

### ISSUE THREAD

**Issue by czepluch** [beamer-bridge/beamer#606]
# Rationale
In the unhappy case that a user creates a request that is not filled (for whatever reason) within the timeout period, we need to have a way in the UI to allow the user to withdraw the tokens that are locked with his request. The functionality is already implemented in the smart contracts, but not in the frontend.

# Implementation
I believe it would be ideal to offer this functionality as part of the "transaction history" overview, so that the user can see if a request wasn't successful and has the options to press a button "withdraw funds" to get back his funds.

I need input from @olympe-silve regarding this and it would be great if it could be included in the design of the transaction history. I am also open to other suggestions, but this currently the best place for this functionality in my opinion.

**Comment by fredo** [comment]
#279 needs to be taken into account here. In order to withdraw tokens from a request the request must be expired **and** does not have any active claims on it. If that is the case then we need to wait until all active claims are resolved. This takes at least 8 days.
Each claim has a termination set, which can be prolonged if the challenge continues. But at least at each point in time we could give the user a feedback that he has to wait at least X time. 


This should be reflected in the UI. Unless a request is filled, the user might ahve the opportunity to withdraw the tokens in the future. There will be a timestamp when the user can withdraw the tokens. We should give the user this timestamp as feedback `withdrawable in XXX` (until it is filled).

Im happy to discuss details

**Comment by fredo** [comment]
indexed keyword on `ClaimMade` events is included in #569
