### ISSUE TITLE
Research how to integrate with Arbitrum

### ISSUE THREAD

**Issue by taleldayekh** [beamer-bridge/beamer#616]
- See if there is any relayer needed
- See how message passing works
- See how gas calculations works
- Block timestamps
- IProofSubmitter
- Contract verification
- Verify that protocol is safe over multiple chains (maybe split from this issue)

### Goal
Should have a set of issues similar as for non-fill of clear tasks for integrating with Arbitrum.

**Comment by cducrest** [comment]
- See if there is any relayer needed

"Auto-Redeem Record: Quasi-transaction ArbOS creates automatically which attempts to redeem a retryable ticket immediately when it is submitted using the ArbGas provided. Attempted / emitted iff gas*gas-price > 0. If it fails, retryable ticket stays in the retry buffer."[1]

My understanding is that if the L1 transaction submitting the L1->L2 message provides enough gas, the L2 message will be automatically executed. Otherwise (if there is no gas or not enough / tx fails) the message will remain as a retryable ticket that can be executed at a later point by a relayer.

source:
[1] https://developer.offchainlabs.com/docs/l1_l2_messages

**Comment by fredo** [comment]
I think whats more interesting is how is L2 -> L1 being executable. 
What we refer to as a relayer comes from optimisms usage. We have a separate tool (relayer) which is able to execute a transaction which was sent from L2 -> L1 in form of a message.

**Comment by cducrest** [comment]
I created issues for e2e testing with arbitrum, as discussed during the daily with Paul, it might be too hard / impossible with the current state of arbitrum. In that case, we should replace the issues with manual testing directly on the testnet. Waiting on response from their discord.

**Comment by istankovic** [comment]
I'm thinking we can close this now and proceed with other issues.
