### ISSUE TITLE
Contract verification on Optimism, Arbitrum and Mainnet

### ISSUE THREAD

**Issue by istankovic** [beamer-bridge/beamer#619]
Create a script to verify contracts on

- [ ] Optimism
- [ ] Mainnet
- [ ] Arbitrum

It can be called by `python scripts/verify-contracts.py <artifacts_dir> <rpc_file>`

Acceptance criteria

- [ ] Implement the script using ape-etherscan
- [ ] Deploy goerli and test it

**Comment by taleldayekh** [comment]
Waiting for https://github.com/eth-brownie/brownie/issues/1591

**Comment by fredo** [comment]
This should be pulled into the backlog once we are working on the new deployment infrastructure.
We need to find a solution though.
An alternative approach which turned out to be successful is verification on the explorer directly. According to @compojoom description we need to fold all imports into one file. For the current version such a document can be found [here](https://gist.github.com/fredo/01d53f36a8eede4f00a1ec23ab4ddd30). In any case, this should also be automated upon deployment.

**Comment by andfletcher** [comment]
I added this issue to the Rework deployment infrastructure Epic

**Comment by istankovic** [comment]
Now that we have ape, we need to consider using it for contract verification instead of rolling our own solution.
At least we should have an idea about the following:
- how hard it is to add support for contract verification on new chains in ape
- the extent of new dependencies we would be using inside the `beamer` Python package (excluding tests)
- possible minimization of dependencies
- potential changes in import times of `beamer`

**Comment by bilbeyt** [comment]
I have found that we need to also implement ape plugins to make it work for new chains like polygon zkevm, so whenever we need to add new chain, we need to create ape plugin and adjust ape-etherscan.
