### ISSUE TITLE
Arbitrum resolver

### ISSUE THREAD

**Issue by cducrest** [beamer-bridge/beamer#625]
We need to use a different resolver than what we currently have for Optimism. The resolver contract needs to call `sendL1FundedContractTransaction(uint256 maxGas, uint256 gasPriceBid, address destAddr, bytes data)` and not `sendMessage(address _target, bytes calldata _message, uint32 _gasLimit)`

Decide if we need to use one resolver for both Optimism and Arbitrum or use two distinct contracts.

See https://github.com/beamer-bridge/beamer/issues/616
https://developer.offchainlabs.com/docs/sol_contract_docs/md_docs/arb-bridge-eth/bridge/inbox

**Comment by fredo** [comment]
Decision
- One Messenger Proxy per rollup instance
- No exchange of contracts in the L1 path. instead do complete redeployment.

1) create Messenger Proxy Interface, Implement Optimism proxy contract, adapt resolver to use the proxy instead of optimism message inbox directly. Documentation.
2)create Messenger Proxy for Arbitrum.
3) deployment script needs to be modified

**Comment by fredo** [comment]
closed in favor of #662, #663, #664
