### ISSUE TITLE
Create messenger proxy for Arbitrum

### ISSUE THREAD

**Issue by fredo** [beamer-bridge/beamer#664]
Arbitrum needs its own messenger proxy. The function signature is `sendL1FundedContractTransaction(uint256 maxGas, uint256 gasPriceBid, address destAddr, bytes data)`.

https://developer.offchainlabs.com/docs/sol_contract_docs/md_docs/arb-bridge-eth/bridge/inbox

**Comment by palango** [comment]
Might help for the `msg.sender` translation: https://developer.offchainlabs.com/docs/l1_l2_messages#address-aliasing

**Comment by istankovic** [comment]
> Arbitrum needs its own messenger proxy. The function signature is `sendL1FundedContractTransaction(uint256 maxGas, uint256 gasPriceBid, address destAddr, bytes data)`.

It is not clear how that would work. Internally, that function uses `L1MessageType_L2FundedByL1`, whch is defined as 
```
uint8 constant L1MessageType_L2FundedByL1 = 7;
```
(nitro/contracts/src/libraries/MessageTypes.sol).

This maps to
```
L2MessageKind_SignedCompressedTx = 7
```
(nitro/arbos/incomingmessage.go)
which is used in
```
    case L2MessageKind_SignedCompressedTx:                                           
        return nil, errors.New("L2 message kind SignedCompressedTx is unimplemented")
```
(nitro/arbos/incomingmessage.go:parseL2Message)

So due to lack of docs and the above, I am guessing that this is not currently supported.
I have also asked Arbitrum people about this on their Discord.

**Comment by istankovic** [comment]
Arbitrum person on Discord:

> we recommend to use retryable ticket in most (if not all) cases
