### ISSUE TITLE
Input validation

### ISSUE THREAD

**Issue by taleldayekh** [beamer-bridge/beamer#829]
## Description of Deliverables(s)

We need to validate user input when entered in Beamer. There should be an error message displayed in the UI if a user enters incorrect input.

@olympe-silve please reach out to @weilbith or @manuelwedler for a brief.

## Specifications

For which platform and in what size/aspect ratio?

**Comment by czepluch** [comment]
@manuelwedler @GabrielBuragev Do you have an idea on how to proceed with this? From my perspective it's currently not viable to wait for the design, so if we can just implement something that looks similar to what we have then it's fine for now.

**Comment by manuelwedler** [comment]
Gabriel is already working on the logic of the validation. We have a meeting with Olympe tomorrow morning. I guess she will be quick with the design changes as it is just showing an error message somewhere to the user. If I am correctly informed that she now has time to work on Beamer, we should be able to finish this very soon. Otherwise we can come up with something own without her.

**Comment by GabrielBuragev** [comment]
My way of doing this without a provided design would be:

- For the displayed text we can use texts like "Amount should not exceed X", "Address must be a valid ETH address" etc.
- From the design perspective we could stick to a normal/bolded text font with the theme's red color `#FF0420` which is already configured in tailwind (need to check with @manuelwedler if that is indeed the correct theme color).
Error messages appear under the inputs when errors are present.
- From the UX perspective, we could stick to aggressive validation in order to have a "guidance" feeling.  Once user starts typing in the input we start validating and show an error message as soon as there is an error in his input value.

Putting this here in case we don't have any progress on the design part.

**Comment by manuelwedler** [comment]
We aligned with @olympe-silve and will basically go with Gabriel's approach. No design update needed. The available amount below the amount input should be hidden in case there is an error. 

Closing as we have #259 for the implementation
