### ISSUE TITLE
 Having the "Target Address" be pre-filled so users do not need to copy and paste

### ISSUE THREAD

**Issue by fredo** [beamer-bridge/beamer#878]
Feedback from several community members

Many have been saying:

since most of the time you are transferring to the same wallet address, it would be better to have the "target address" to be pre-filled

@istankovic - feedback from one of the users on discord

**Comment by manuelwedler** [comment]
This should happen when a user opens the dapp and when the form is reset after a transfer.
In case the user is not connected yet when opening the app, the account address should only be copied into the field after connecting when the user didn't input a value there before.

**Comment by GabrielBuragev** [comment]
I think prefilling the address when the form is reset after a transfer might bring up confusion to the users. 

Example:
- User manually writes a different address than his own wallet address as destination address for sending the tokens
- Submits the request and gets redirected to the `Activity` tab
- At this moment we would swap his manually written address with his own wallet address without him knowing that
- User realizes he needs to send a few more tokens to the same destination address
- Goes back to transfer view where destination address is prefilled making him think we didnt change anything in that input field since the last request, so he completely ignores it
- Fills up the amount of tokens and token type and sends transfer
- Funds are being transfered to his own wallet address on another L2
