### ISSUE TITLE
Inform users when they have insufficient balance before initiating transfer

### ISSUE THREAD

**Issue by DocSmoove** [beamer-bridge/beamer#915]
Idea from the community 

# Rationale

Why should this feature exist?
Users sometimes do not see if they have sufficient assets for the transfer. It is better to show it at the beginning before the user initiatives a transfer

What are the use-cases?
When users do not have enough assets or not enough assets to pay fees

Insufficient assets should be informed here
<img width="324" alt="Screenshot_2022-08-08_at_11 25 32_AM" src="https://user-images.githubusercontent.com/107990484/183388075-ec2796a7-1a22-40a2-b1bd-7d3c62464798.png">

Instead of here
<img width="324" alt="Screenshot_2022-08-08_at_11 27 06_AM" src="https://user-images.githubusercontent.com/107990484/183388121-488c0c7a-025b-453c-bac9-e198c52515b3.png">

**Comment by GabrielBuragev** [comment]
@DocSmoove Once again, thanks for reporting and providing such detailed info for this issue.

This issue is also tackled currently by the input validation implementation. 
Form will be unsubmittable (submit button marked as `disabled`) until user enters correct input values for all fields.

Users will get feedback for all invalid cases:
- Insufficient balance (token amount + fees > token balance)
- Invalid token amount input (negative amounts, not matching decimals with Token allowed decimals, other edge cases where inputted value is not a proper numeric value)
- Invalid ETH address

Addressed by issue #259

**Comment by DocSmoove** [comment]
@GabrielBuragev Ok awesome :D Thank you!
