### ISSUE TITLE
Git tracking local files related to ganache deployment

### ISSUE THREAD

**Issue by GabrielBuragev** [beamer-bridge/beamer#921]
After setting up the local test environment (with ganache) using the "contributing" docs: https://docs.beamerbridge.com/contributing.html
i noticed that some of the test files are tracked by git.
To be more specific:

- `deployments/ganache-local` folder
- test-tokens.json
- 0x*.json

This files should be ignored (inside .gitignore) since they are related to the local setup.
@istankovic @fredo what are your thoughts on this?

**Comment by istankovic** [comment]
>     * `deployments/ganache-local` folder
> 
>     * test-tokens.json
> 
>     * 0x*.json
> 
> 
> This files should be ignored (inside .gitignore) since they are related to the local setup. @istankovic @fredo what are your thoughts on this?

I don't think these should be added to `.gitignore` because in the docs they are merely examples of filenames, which could change anytime. Whoever is reading the docs is free to choose filenames but we had to choose _some_ filenames in order to make the examples work and easy to follow.

Additionally, if we change the filenames in the docs, should we then update `.gitignore`? Should we also update `.gitignore` whenever we add another filename (example) to the docs? That does not feel right.

**Comment by fredo** [comment]
I agree with @istankovic on this topic. gitignore should contain files which have consistent naming, are generated or used during development and is something what we really want to make sure, it should not be on remote.

**Comment by GabrielBuragev** [comment]
Okay, thanks for the feedback from both sides!
