### ISSUE TITLE
Frontend: MetaMask button enabled when not installed

### ISSUE THREAD

**Issue by manuelwedler** [beamer-bridge/beamer#937]
#### Expected behavior
In the wallet connection screen, in case the user does not have MetaMask installed the MetaMask button should be disabled + greyed out and/or a message should be shown that the user does not have MetaMask installed.

#### Actual behavior
The button is shown as usual and nothing happens when clicked.

**Comment by GabrielBuragev** [comment]
I suggest that we just redirect the user to the Metamask Extension download page (https://metamask.io/download/) instead of disabling the button.

**Comment by GabrielBuragev** [comment]
We have to check how this will work on mobile devices.
[MetaMask/metamask-onboarding](https://github.com/MetaMask/metamask-onboarding) library that allows redirection after metamask installation to the caller app (beamer in our case).
We could use it in order to retain some flow when we redirect the user to the install page.

Regarding mobile device support, there is an [open PR](https://github.com/MetaMask/metamask-onboarding/pull/86) for supporting that as well. Not sure when it will get merged tho.
