### ISSUE TITLE
Frontend shows tx failed even if the tx went through on both rollups

### ISSUE THREAD

**Issue by czepluch** [beamer-bridge/beamer#968]
#### System information

OS & Version: MacOS
Browser & Version: Firefox

#### Expected behavior
In general I expect transfers to go through and for the frontend to show me that they went through if they did so. I also expect the frontend to show me if a tx fails.

#### Actual behavior
I don't expect the frontend to show me that a transfer failed when the transactions actually went through on both rollups. 

<img width="345" alt="Screenshot 2022-08-25 at 10 20 19" src="https://user-images.githubusercontent.com/1026799/186614163-9a0e4ac7-1cce-4516-b15b-2f77bda24710.png">

I will share the tx hash in private upon request if relevant.

#### Steps to reproduce the behavior
It looks like this consistently happen when transferring 0.5 USDC from Boba to Optimism.

**Comment by czepluch** [comment]
This is all I see in the browser console.
<img width="1439" alt="Screenshot 2022-08-25 at 10 26 21" src="https://user-images.githubusercontent.com/1026799/186614922-7564b3cf-d15c-4002-bff1-102658173efc.png">

**Comment by fredo** [comment]
can you also post a screenshot from the developer console, please?

**Comment by czepluch** [comment]
Did it in RC. Can't do it without showing the url

**Comment by GabrielBuragev** [comment]
This issue seems to be unreproducible. 
@czepluch Can you check one more time if you still get this error?

**Comment by GabrielBuragev** [comment]
Thanks to the info provided i was able to spot some unhandled cases in the code:
- The returned value from the [provider.getTransaction()](https://github.com/beamer-bridge/beamer/blob/main/frontend/src/services/transactions/request-manager.ts#L74) call is not properly checked for null value. Looking at the [etherjs docs](https://docs.ethers.io/v5/api/providers/provider/#Provider-getTransaction) the return value can be null in several cases.
- The returned value from [transaction.wait()](https://github.com/beamer-bridge/beamer/blob/main/frontend/src/services/transactions/request-manager.ts#L75) is not properly checked for null value. Looking at the [etherjs docs](https://docs.ethers.io/v5/api/providers/types/#providers-TransactionResponse) the return value can also be null for transactions that havent been mined. 
This function also throws errors which can be catched and used to show the proper messages to the user.

**Comment by czepluch** [comment]
It consistently happen to me every time I try to transfer from Boba to Optimism.

**Comment by GabrielBuragev** [comment]
So, after a debugging session with @czepluch we concluded that he was using `https://mainnet.boba.network` instead of `https://replica.boba.network` as an RPC url in his "Boba Mainnet" network configuration. 

There were already errors reported many times in the past when the app was tested while using `https://mainnet.boba.network` as an RPC endpoint for mainnet boba.

Also, my previous [comment](https://github.com/beamer-bridge/beamer/issues/968#issuecomment-1232905392) on this issue is still valid and falls under the scope of this issue. Since the networks/rpc endpoints can behave weird from time to time we need to make the app more robust by handling those exceptions.

@andfletcher i suggest you try to change the RPC url used inside your "Networks" configuration in Metamask for "Boba Mainnet" from `https://mainnet.boba.network` to `https://replica.boba.network` and then test again if the error still occurs.

**Comment by andfletcher** [comment]
I was using https://replica.boba.network
